テンプレート追加
opensource-workshop/connect-cms pull request #1058
Opened 2021-12-24 04:45 UTC by osws-makino

データベース検索に「card_04」テンプレ追加
データベース検索でソート機能追加
新着に「card_04」テンプレ追加

## 概要

- データベース検索プラグインに「card_04」という、カードタイプで１行に４個並ぶテンプレートを追加
- データベース検索プラグインに、表示データを「登録順」「更新順」「公開日順」「表示項目順」でソートする機能を追加
- しんちゃくプラグインに「card_04」という、カードタイプで１行に４個並ぶテンプレート追加

## 関連Pull requests/Issues
なし

## 参考

## DB変更の有無
有り
「sort_flag」追加

## チェックリスト

- [ ] PHP_CodeSnifferを実行して、本PR内に指摘が存在しないことを確認しました。https://github.com/opensource-workshop/connect-cms/wiki/PHP_CodeSniffer

- [ ] オンラインマニュアルの更新 https://connect-cms.jp/manual

2021-12-27 09:23 UTC, gakigaki requested changes
ご確認よろしくお願いします

2021-12-28 00:15 UTC, osws-makino commented on resources/views/plugins/user/databasesearches/card_04/databasesearches.blade.php
> + * @author 永原　篤 <nagahara@opensource-workshop.jp>
自分の名前を追記しましたー。

2021-12-28 00:16 UTC, osws-makino commented on app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php
> +use function Psy\debug;
コレ、なんで追加したんだったっけな？
不要な気がするので削除します。

2021-12-28 00:20 UTC, osws-makino commented on resources/views/plugins/user/databasesearches/card_04/databasesearches.blade.php
> +                                {{-- 一旦、WYSIWYGのみHTMLエスケープ除外。resources\views\plugins\user\databases\default\databases_include_value.blade.phpと同様にするかは次の機会に検討する --}}
これ、コピーしてきたdefaultにもついていたのでそのまま残してあるだけですね。
関連するissueはないようです。これ、誰が残したものなんだろう？　永原さんかな。

2021-12-28 00:21 UTC, osws-makino commented on resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php
> +@if (isset($whatsnews_frame->rss) && $whatsnews_frame->rss == 1)
定数に変更しますねー。

2021-12-28 00:23 UTC, osws-makino commented on app/Enums/DatabaseSearcherSortFlag.php
> +    }
了解です。

2021-12-28 00:25 UTC, osws-makino commented on app/Enums/DatabaseSearcherSortFlag.php
> +    }
消しまーす。

2021-12-28 00:26 UTC, osws-makino commented on resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php
> +                        v-bind:class="{ 'border': border == '1' }"
やってみます。

2021-12-28 00:27 UTC, osws-makino commented on resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php
> +                        <dd v-if="view_posted_at == 1" class="text-center whatsnew_posted_at">
やってみます。

2021-12-28 00:27 UTC, osws-makino commented on resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php
> +                        <dd v-if="thumbnail == '1' && whatsnews.first_image_path" class="text-center whatsnew_thumbnail">
やってみます。

2021-12-28 00:27 UTC, osws-makino commented on resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php
> +                        <dd v-if="view_posted_name == 1" class="text-center whatsnew_posted_name">
やってみます。

2021-12-28 10:17 UTC, gakigaki commented on app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php
> +                break;
@osws-makino 
これはどうでしょうか？
デフォルトソートは表示順の昇順でよいかと思います。

2021-12-28 10:17 UTC, gakigaki commented on resources/views/plugins/user/databasesearches/card_04/databasesearches.blade.php
> +                                {{-- 一旦、WYSIWYGのみHTMLエスケープ除外。resources\views\plugins\user\databases\default\databases_include_value.blade.phpと同様にするかは次の機会に検討する --}}
@nagasheep 
このコメントについて教えてください。

2022-01-06 03:14 UTC, gakigaki commented on resources/views/plugins/user/databasesearches/card_04/databasesearches.blade.php
> +                                {{-- 一旦、WYSIWYGのみHTMLエスケープ除外。resources\views\plugins\user\databases\default\databases_include_value.blade.phpと同様にするかは次の機会に検討する --}}
永原さんに確認しました。
結論から言うと、このコメントは削除してOKです。

このコメントは結構古いものでした。
コメント当時、WYSIWYGのHTML記述制限がなかったようです。
そのため、いったんここは許可するけど、後で問題ないか検討しようと思い、このコメントを残されたそうです。
現在は、サイト管理のHTML記述制限があるため、このコメントは不要となりました。

2022-01-06 06:33 UTC, osws-makino commented on resources/views/plugins/user/databasesearches/card_04/databasesearches.blade.php
> +                                {{-- 一旦、WYSIWYGのみHTMLエスケープ除外。resources\views\plugins\user\databases\default\databases_include_value.blade.phpと同様にするかは次の機会に検討する --}}
コメント削除しました。

2022-01-06 06:33 UTC, osws-makino commented on app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php
> +                break;
defaultの場合、登録順の昇順にソートするようにしました。

2022-01-06 06:39 UTC, gakigaki approved these changes
ご対応ありがとうございました！
マニュアルの修正をよろしくお願いします。

2022-01-06 06:50 UTC, osws-makino commented
データベース検索のマニュアルを修正しましたー。

2022-01-06 06:53 UTC, gakigaki commented
ありがとうございます！
マージします。

2022-01-06 06:53 UTC, merged