ハンバーガーメニューを追加
opensource-workshop/connect-cms pull request #1122
Opened 2022-02-04 03:13 UTC by osws-makino

メニュープラグインにハンバーガーメニューテンプレート追加

## 概要
メニュープラグインに、ハンバーガーメニューテンプレート追加
メニュー本体の仕様は「ディレクトリ展開式」をそのまま利用しています。

## DB変更の有無
なし
## チェックリスト

- [ ] PHP_CodeSnifferを実行して、本PR内に指摘が存在しないことを確認しました。https://github.com/opensource-workshop/connect-cms/wiki/PHP_CodeSniffer

- [ ] オンラインマニュアルの更新 https://connect-cms.jp/manual
- [ ] (DB変更有りの場合) 移行プログラムに影響がない事を確認しました。https://github.com/opensource-workshop/connect-cms/wiki/Pull-requests-check-list---Migration

2022-02-04 06:10 UTC, gakigaki commented
メイン部にコンテンツがない状態だと、小さな縦スクロールが出てきメニューが隠れてしまいます。
<img width="960" alt="image" src="https://user-images.githubusercontent.com/32890286/152480779-d755c015-286e-4095-9c7c-067a5ff452fb.png">

.hamburger-menuのpositionをfixedに変更して、位置の微調整で直るかもしれないです。

2022-02-04 06:45 UTC, gakigaki requested changes
確認お願いします。

2022-02-04 06:45 UTC, gakigaki commented on resources/views/plugins/user/menus/hamburger_button/menus.blade.php
> +{{--
このファイルですがほとんでdefaultと同じかと思います。
どうにか共通化できないでしょうか？
defaultとの共通部分に修正が発生した場合、修正に時間がかかったり、修正漏れを防ぐようにしたいです。

2022-02-04 06:52 UTC, osws-makino commented on resources/views/plugins/user/menus/hamburger_button/menus.blade.php
> +{{--
どうにかしたいですねぇ。

2022-02-04 06:56 UTC, gakigaki commented on resources/views/plugins/user/menus/hamburger_button/menus.blade.php
> +{{--
blogのdatefirstテンプレートが参考になりそうです！
@akagane99 thx!!

2022-02-04 07:03 UTC, osws-makino commented on resources/views/plugins/user/menus/hamburger_button/menus.blade.php
> +{{--
defaultテンプレートじゃなくって、opencurrenttree（ディレクトリ展開式）を丸ごとコピーしてきました。
なので、opencurrenttreeのmenu.blade.phpをincludeで呼び出し可能にしてみます。

2022-02-04 07:05 UTC, osws-makino commented
@gakigaki 
共通部分をincludeで呼び出し式にして、
ハンバーガーのメニュー部分を、hiddenからclipに変更してみました。

2022-02-04 07:33 UTC, gakigaki reviewed
修正ありがとうございます。
2点コメントしたので、ご確認お願いします。

2022-02-04 07:33 UTC, gakigaki commented on resources/views/plugins/user/menus/hamburger_button/menus_script.blade.php
> +        overflow-x: clip;
htmlとbody指定だと範囲が広すぎるので、影響がないか心配です。
.hamburger-menu-areaに含める形ではだめですか？

2022-02-04 07:33 UTC, gakigaki commented on resources/views/plugins/user/menus/hamburger_button/menus.blade.php
> +{{--
修正ありがとうございます。
おそらくopencurrenttreeがdefaultのコピーなので、そこがblogのdatefirstテンプレートのようにならないでしょうか？
今回の修正範囲から拡大して申し訳ないのですが、確認お願いします。

2022-02-04 07:57 UTC, osws-makino commented
これは……ちょっと難しそうですねぇ……
どうしたもんか。

2022-02-07 06:15 UTC, osws-makino commented
こんな感じで起票しました。
https://github.com/opensource-workshop/connect-cms/issues/1141

2022-02-07 07:09 UTC, osws-makino commented on resources/views/plugins/user/menus/hamburger_button/menus_script.blade.php
> +        overflow-x: clip;
それでいきましょう！

2022-02-07 07:13 UTC, gakigaki approved these changes
OKです！ありがとうございました！

2022-02-07 07:13 UTC, merged