Add: cURL実行の共通化
opensource-workshop/connect-cms pull request #1160
Opened 2022-02-10 13:45 UTC by gakigaki

## 概要

WebAPI実行を共通処理にしました。

テストコードも合わせてコミットしています。

### 確認事項

細かなことですが、初めてTraitを作成するので、クラス名、名前空間で悩んでいます。

### クラス名

案

- ExecutesWebApi
- ExecutesCurl

Laravel本体のTraitを見ると、以下のような命名規則がよさそうです。

- 三単現動詞+目的語
  - 共通処理
- 形容詞 -able
  - interfaceのようにふるまいを持たせる
- 複数形名詞
  - プロパティ用

### 名前空間

- App\Traits
  - Connect-CMSだと、ここがTrait置き場？

## 関連Pull requests/Issues

#1159

## 参考

## DB変更の有無

無し

## チェックリスト

- [x] PHP_CodeSnifferを実行して、本PR内に指摘が存在しないことを確認しました。https://github.com/opensource-workshop/connect-cms/wiki/PHP_CodeSniffer

- [x] オンラインマニュアルの更新 https://connect-cms.jp/manual
- [x] (DB変更有りの場合) 移行プログラムに影響がない事を確認しました。https://github.com/opensource-workshop/connect-cms/wiki/Pull-requests-check-list---Migration

2022-02-11 01:26 UTC, akagane99 requested changes
見直しよろです。

2022-02-11 01:26 UTC, akagane99 commented on app/Traits/ExeceutesWebApi.php
> +trait ExeceutesWebApi
作りがUtilitiesっぽいので、まずは下記どっちでいくか再検討かなぁ。
・traitのままいく（※）
・Utilitiesに変更する

※ traitはメソッドを「はやす」処理なんで、execute()、buildOptions()等、useしたクラスでバッティングや意味理解が難しいかな。privateでもuseしたクラスでは使えちゃう。
　traitのままいくなら、ここらへんはメソッド名変えた方が良さそう。


Utilitiesサンプル
https://github.com/opensource-workshop/connect-cms/blob/master/app/Utilities/Token/TokenUtils.php

参考：[PHP] Trait の private は使用しているクラス上では普通に使える件
https://qiita.com/niisan-tokyo/items/24d94c98c4df2ce6990d

2022-02-11 01:26 UTC, akagane99 commented on app/Traits/ExeceutesWebApi.php
> +    private function addProxyOptions(array $options)
細かい事。メソッドの返り型の定義忘れ。

2022-02-11 01:26 UTC, akagane99 commented on app/Traits/ExeceutesWebApi.php
> +    public function setTimeout(int $timeout)
細かい事。メソッドの返り型の定義忘れ。

2022-02-11 01:26 UTC, akagane99 commented on app/Traits/ExeceutesWebApi.php
> +trait ExeceutesWebApi
（trait or Utilitiesの再検討した後で）これ使ったクラスが１個あると、イメージしやすいかな。
どこか実装できる？

2022-02-12 02:47 UTC, masaton0216 commented
- traitのままだとprivate系の汎用ちっくなメソッドがプラグインのコントローラーとバッティングしてしまう可能性は同感です。直すなら既にあるUtilityクラスに揃えてしまうのが早いのかな？これならバッティング問題は考えなくて済むのかしら
- staticにしてFacadeっぽく呼び出してるほうが、そのメソッド追う時に個人的には分かりやすいので、そういう意味でもTokenUtility形式に一票なキモチ

2022-02-14 07:01 UTC, gakigaki commented on app/Traits/ExeceutesWebApi.php
> +trait ExeceutesWebApi
traitのprivateメソッドが思ってたprivateではないとは……(´・ω・｀)

2022-02-14 07:03 UTC, gakigaki commented
**Utitilty or Trait?**
タイムアウト秒数を呼び出す側からtraitのフィールド変数で変えられるようにしているので、
traitがいいかなあと思っている次第です。
staticメソッドにすると、今後の変更でタイムアウト秒数のようなオプション設定を追加するとき
引数がどんどん増えてきそうなイメージがあります。それは、避けたいところです。

2022-02-14 07:03 UTC, gakigaki commented on app/Traits/ExeceutesWebApi.php
> +trait ExeceutesWebApi
テストコードが実装イメージになるかと思います！

2022-02-14 08:05 UTC, akagane99 commented on app/Traits/ExeceutesWebApi.php
> +trait ExeceutesWebApi
(´・ω・｀)

2022-02-14 08:06 UTC, masaton0216 commented on app/Traits/ExeceutesWebApi.php
> +trait ExeceutesWebApi
(  ´・ω・`)

2022-02-14 08:09 UTC, akagane99 commented on app/Traits/ExeceutesWebApi.php
> +trait ExeceutesWebApi
なるほど、そう使うのね。

現行、Connectで`curl_init()`を使ってるとこ検索してみた。
ここにフィットする形がいいのかなぁ。
https://github.com/opensource-workshop/connect-cms/search?l=PHP&q=curl_init

2022-02-14 08:22 UTC, gakigaki commented on app/Traits/ExeceutesWebApi.php
> +trait ExeceutesWebApi
フィットするようにはなっているかと思います。
executeCurl()でURL、HTTPメソッド、パラメーターを設定できます。
executeCurl()の戻り値が配列になっていて、'info'にcurl_info()の(値)[https://www.php.net/manual/ja/function.curl-getinfo.php#refsect1-function.curl-getinfo-returnvalues]、'body'にレスポンスボディが入ります。

2022-02-14 08:41 UTC, akagane99 commented on app/Traits/ExeceutesWebApi.php
> +trait ExeceutesWebApi
え、まじで？

Manageコントローラと、app/Plugins/Apiと、ConnectCommonTraitと、Core/UploadControllerの４種類に
このpublicメソッドが生える事になるんだけど、それって変に感じるなぁ。

処理見直さないと、何とも言えないなぁ。。

app/Plugins/Manage/IndexManage/IndexManage.php
app/Plugins/Api/Translate/Translate.php
app/Traits/ConnectCommonTrait.php
app/Http/Controllers/Core/UploadController.php

2022-02-14 08:57 UTC, gakigaki commented on app/Traits/ExeceutesWebApi.php
> +trait ExeceutesWebApi
CC本体がコントローラーファットだったの忘れてた……。
もともとサービスに外部WebAPIを実行できるというふるまいを持たせたく作ったんですが、
こうなるとUtilityにするしかなさそうな感じですかね。

2022-02-15 00:27 UTC, akagane99 commented on app/Traits/ExeceutesWebApi.php
> +trait ExeceutesWebApi
・そうだねぇ。いまんとこはUtility位かなぁ。（手間少ない、影響少ない）

・ あとはUtilityと似てるけど、ファサードにする案もあるけど、テストしやすい位で、Utilityとあんまし変わらないかなぁ。（しかし、ファサードはコネクト実装例なし。うーん）

・Traitでいくとなると、timeoutとかメソッド名の命名変更（curl_timeoutとか、curl関連ってわかるように変更→メソッドは長めになるかなぁ💦）すれば、ある程度いけるけど、
　ConnectCommonTrait.phpがやっかいで、Traits/ExeceutesWebApi.php をuse すると、ConnectCommonTrait使ってるクラスすべてに、ExeceutesWebApiが生えるというカオスに・・・w;

（うーん悩ましいー）

　

2022-02-15 01:40 UTC, masaton0216 commented
引数どんどん増えちゃう懸念があるなら、割り切ってそれらのパラメータをenv外出しにしてみてはどうかしら
一律にはなってしまうけど今今の要求範囲内では一律で問題ないし、呼び出し毎に変えたい要求が出てきた場合は少し手直しすれば進めると思う。

2022-02-15 01:59 UTC, gakigaki commented
@akagane99 @masaton0216 
アドバイスありがとうございます！
以下で対応したいと思います！

- Utilityクラスにする
- タイムアウト秒数などのcURL設定値は.envへ

設定値を変えたい場合はUtilityを呼び出す前にconfig()で値変えられますね！

2022-04-11 03:13 UTC, gakigaki commented
@akagane99 @masaton0216 
長らく放置していましたが、対応しました！

> Utilityクラスにする
> タイムアウト秒数などのcURL設定値は.envへ

再度のご確認をお願いいたします。

2022-04-11 04:13 UTC, akagane99 reviewed
レビューOK

2022-04-13 07:40 UTC, merged

2022-04-13 07:40 UTC, gakigaki commented
レビューありがとうございました！