Fix: ZIPファイルのインポートエラー
opensource-workshop/connect-cms pull request #1256
Opened 2022-04-07 09:30 UTC by gakigaki

## 概要

解凍先パスの指定が誤っていたようです。

元のコメントからすると、Windowsで作成したZIPファイル用に敢えて"\*/\*.csv"にしていたと読めます。
ただ、私の環境(Debian)では、一時フォルダ直下に解凍ファイルが作られます。
Windowsで作成したZIPファイルで動作確認したので、この修正内容で問題ないかとは思います。

## 関連Pull requests/Issues

* #1255

## 参考

## DB変更の有無

無し

## チェックリスト

- [x] オンラインマニュアルの更新 https://connect-cms.jp/manual
- [x] (DB変更有りの場合) 移行プログラムに影響がない事を確認しました。https://github.com/opensource-workshop/connect-cms/wiki/Pull-requests-check-list---Migration

2022-04-07 09:59 UTC, akagane99 reviewed
レビューOK！
（正直コードからはOK/NG判別できんかった💦。動作確認してくれてるから問題ないと思います。）

2022-04-07 22:18 UTC, akagane99 requested changes
ごめん、まった。
connect公式サイトで確認したらzipインポートできた。
一度解説します。

2022-04-07 22:29 UTC, akagane99 commented
以下公式サイトでzipインポート試し。（データベース１の都道府県データベース、立ち入り禁止県のデータ）
https://connect-cms.jp/test/database#frame-142

以下のzipファイルでインポートできました。
[database.zip](https://github.com/opensource-workshop/connect-cms/files/8447153/database.zip)

zipのフォルダ構成は旧オンラインマニュアルで。
https://connect-cms.jp/manual/user/database#frame-178

> Windowsで作成したZIPファイルで動作確認したので、この修正内容で問題ないかとは思います。

Windowsの標準機能で作成するZIPファイルって下記の事なんだけど、これでテストしてくれたって事だったかな？
これにしてるのは、学校の先生達のＰＣに開発者が使ってるような zipツールをインストールしてない事が考えれるからなんだ。
![image](https://user-images.githubusercontent.com/2756509/162329219-d8eee192-e3fb-4ca2-97a6-06d441c7f7e9.png)

修正後もこの形式のzipファイルをインポートできれば問題ないかと。

2022-04-08 02:02 UTC, gakigaki commented
インポートのZIPファイルはアップロードファイルを含めたものだったんですね。
WindowsのエクスプローラーからCSVファイルを右クリックしてZIPファイルを作っていました。

画面のメッセージからZIPファイルはアップロードファイルを含むものと読み取れなかったので、
説明書きを強化する形で対応したいと思います。

2022-04-08 04:00 UTC, akagane99 commented
すません、ありがとう🙇‍♂️

2022-04-08 04:33 UTC, gakigaki commented
このPRはクローズして別PR作ります。

2022-04-08 04:33 UTC, closed without merging