Add: FAQの投稿者名表示
opensource-workshop/connect-cms pull request #1312
Opened 2022-06-17 09:27 UTC by gakigaki

## 概要

FAQに投稿者名を表示する機能を追加しました。

## レビュー完了希望日

6/30（木）

## 関連Pull requests/Issues

## 参考

## DB変更の有無

無し

## チェックリスト

- [ ] オンラインマニュアルの更新 https://connect-cms.jp/manual
- [ ] (DB変更有りの場合) 移行プログラムに影響がない事を確認しました。https://github.com/opensource-workshop/connect-cms/wiki/Pull-requests-check-list---Migration

2022-06-18 07:32 UTC, akagane99 requested changes
FaqFrameConfigアップ後に再レビューで。

2022-06-20 01:18 UTC, gakigaki commented on app/Plugins/User/Faqs/FaqsPlugin.php
> +use App\Enums\FaqFrameConfig;
アップし忘れすみません！
追加コミットしました！

2022-06-20 01:19 UTC, gakigaki commented on app/Plugins/User/Faqs/FaqsPlugin.php
> +use App\Enums\FaqFrameConfig;
追加コミットのメッセージを間違えましたが、スカッシュマージで消すのでスルーでお願いします。

2022-06-20 01:21 UTC, akagane99 commented on app/Plugins/User/Faqs/FaqsPlugin.php
> +use App\Enums\FaqFrameConfig;
らじゃ。

bladeで FaqFrameConfig つかってるので、app.phpだっけ？にエイリアスを追加してるだろうから、そっちもアップお願い＞＜

2022-06-20 01:22 UTC, gakigaki commented on app/Plugins/User/Faqs/FaqsPlugin.php
> +use App\Enums\FaqFrameConfig;
そっちもも漏れてましたね……sry

2022-06-20 01:25 UTC, akagane99 approved these changes
レビューOK

2022-06-20 01:27 UTC, gakigaki commented
レビューサンキューです！

2022-06-20 01:37 UTC, gakigaki commented
ラジオでON・OFF時、左側はOFFで統一の件で、「RSSの表示」の対応が漏れていたので修正しました。
<img width="406" alt="image" src="https://user-images.githubusercontent.com/32890286/174510519-8afe7d5b-c191-4320-8d82-a23d7379e05c.png">

2022-06-20 01:53 UTC, akagane99 approved these changes
再レビューOK！

2022-06-21 06:03 UTC, masaton0216 approved these changes
LGTM！

2022-06-27 01:38 UTC, merged