OW-1111 ユーザインポートでログインユーザは更新できないようにする
opensource-workshop/connect-cms pull request #1363
Opened 2022-07-11 05:22 UTC by masaton0216

## 概要
https://github.com/opensource-workshop/connect-cms/issues/1353

## レビュー完了希望日
7月25日（月）

## 関連Pull requests/Issues
https://github.com/opensource-workshop/connect-cms/issues/1353

## 参考
なし

## DB変更の有無
なし

## チェックリスト

- [x] オンラインマニュアルの更新 https://connect-cms.jp/manual
- [x] (DB変更有りの場合) 移行プログラムに影響がない事を確認しました。https://github.com/opensource-workshop/connect-cms/wiki/Pull-requests-check-list---Migration

2022-07-11 08:15 UTC, akagane99 requested changes
レビューしたよー。修正検討よろです。
必要あったらzoom相談とかもOKです。

2022-07-11 08:15 UTC, akagane99 commented on resources/views/plugins/manage/user/import.blade.php
> +                    @include('common.errors_inline', ['name' => 'character_code'])
デグレってるよー。
'plugins.common.errors_inline'　が正解。
'common.errors_inline' は非推奨。
https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/common/errors_form_line.blade.php

2022-07-11 11:43 UTC, masaton0216 commented on resources/views/plugins/manage/user/import.blade.php
> +        if( !confirm('{{CsvCharacterCode::enum[CsvCharacterCode::sjis_win]}}で現在の絞り込み条件のユーザをダウンロードします。\nよろしいですか？') ) {
脳死コピペすいません。こんな感じでどうでしょう？
![image](https://user-images.githubusercontent.com/13323806/178256905-48462f4c-b23d-44d8-a547-84004687bd2c.png)

2022-07-11 11:46 UTC, masaton0216 commented on resources/views/plugins/manage/user/import.blade.php
> +                                </button>
@gakigaki の提案に一理あるなー（注釈近傍にボタンがあった方がわかりやすい。画面遷移の手間も減る）とも思ったので置いてみました。・・・位置に関しては少し横着しました（笑）

2022-07-11 11:46 UTC, masaton0216 commented on resources/views/plugins/manage/user/import.blade.php
> +                    @include('common.errors_inline', ['name' => 'character_code'])
すいません、これは見落としてました。ありがとうございます。

2022-07-11 11:47 UTC, masaton0216 commented
@akagane99 指摘対応を入れました！

2022-07-11 12:02 UTC, akagane99 commented on resources/views/plugins/manage/user/import.blade.php
> +                                </button>
おっけー

2022-07-12 01:39 UTC, gakigaki approved these changes
LGTM

2022-07-12 01:49 UTC, merged