[コア：アップロードファイル] ファイルの削除機能を追加しました
opensource-workshop/connect-cms pull request #1546
Opened 2023-01-11 04:51 UTC by masaton0216

## 概要
 - 管理機能－アップロードファイルのファイル詳細画面にファイルの削除機能を追加しました。
![image](https://user-images.githubusercontent.com/13323806/211719009-48c5ba4f-600e-45e1-bea7-044d73ea02f7.png)

 - 併せて、ファイル参照不可時に404を返すように修正しています。ノーイメージ画像を表示することに理由がある場合は突っ込んでください。
 - 尚、懸念していたフォトアルバム／キャビネット等で、管理機能からのファイル削除後に各プラグインの挙動確認を行いました。エラー等で表示ができなくなる等もなく、各プラグインデータとしての削除も可能だった為、特に問題はないと思われます。
     - 削除後の画面イメージ（キャビネット）
![image](https://user-images.githubusercontent.com/13323806/211720123-1f601415-7231-4bbd-ab6b-c024606db24c.png)

     - 削除後の画面イメージ（フォトアルバム）
![image](https://user-images.githubusercontent.com/13323806/211720170-13c58e06-0d61-46ab-ad65-207f495b1645.png)

## レビュー完了希望日
1/18（水）

## 関連Pull requests/Issues
https://github.com/opensource-workshop/connect-cms-ideas/issues/73

## 参考
なし

## DB変更の有無
あり

## チェックリスト

- [x] (DB変更有りの場合) 移行プログラムに影響がない事を確認しました。https://github.com/opensource-workshop/connect-cms/wiki/Pull-requests-check-list---Migration
- [x] プルリクエストにわかりやすいタイトルとラベルを付けました。https://github.com/opensource-workshop/connect-cms/wiki/Pull-requests-Rule

2023-01-11 06:19 UTC, akagane99 requested changes
レビューしました。確認よろですー

2023-01-11 06:19 UTC, akagane99 commented on app/Plugins/Manage/ManagePluginBase.php
> +    use ConnectCommonTrait;
アップロードの削除対応で親のManagePluginBase.phpにuse ConnectCommonTrait;する理由はなんだろう？

UploadfileManage.phpでConnectCommonTraitの処理は追加されてないように見えるのだけれど。

2023-01-11 06:19 UTC, akagane99 commented on app/Models/Common/Uploads.php
> +    use SoftDeletes;
論理削除にする場合、Connect全体でUploadsテーブルとjoinしている処理の影響は調査した感じ？

2023-01-11 06:19 UTC, akagane99 commented on app/Models/Common/Uploads.php
> +    use SoftDeletes;
物理ファイルは消してるけど、データは論理削除にする理由はなんだろ？

2023-01-11 06:19 UTC, akagane99 commented on app/Plugins/Manage/UploadfileManage/UploadfileManage.php
> +        $upload = Uploads::findOrFail($uploads_id);
データ無かった場合、表示どうなるんだろう？
同じように:findOrFail()つかってるとこ、あるんだっけ？

2023-01-11 06:19 UTC, akagane99 commented on database/migrations/2023_01_11_105812_add_deleted_to_uploads.php
> +            $table->softDeletes();
削除のdeleted_id、deleted_nameってこれ入るんだっけ？

参考）
bbsesテーブル

2023-01-11 06:19 UTC, akagane99 commented on resources/views/plugins/manage/uploadfile/index.blade.php
> +
@include('plugins.common.flash_message')
使って―

参考）ユーザ管理
https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/plugins/manage/user/list.blade.php#L53-L54

https://github.com/opensource-workshop/connect-cms/blob/master/app/Plugins/Manage/UserManage/UserManage.php#L796

https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/plugins/common/flash_message.blade.php

2023-01-11 06:22 UTC, gakigaki reviewed
ご対応ありがとうございます。
レビューしたので、ご確認よろしくお願いします。

2023-01-11 06:23 UTC, masaton0216 commented on app/Http/Controllers/Core/UploadController.php
> -            return response()->download(storage_path(config('connect.no_image_path')));
これにて「connect.no_image_path」へのお役御免（参照ゼロ）です。
大元は使う機会あるのかなと残してあります。

2023-01-11 06:23 UTC, gakigaki commented on app/Plugins/Manage/UploadfileManage/UploadfileManage.php
> +        $upload = Uploads::findOrFail($uploads_id);
L210の$this->getDirectory($upload->id)ですかね

2023-01-11 06:24 UTC, masaton0216 commented on app/Plugins/Manage/ManagePluginBase.php
> +    use ConnectCommonTrait;
ConnectCommonTrait.getDirectory()を参照しています。

2023-01-11 06:24 UTC, gakigaki commented on app/Plugins/Manage/ManagePluginBase.php
> +    use ConnectCommonTrait;
L210の$this->getDirectory($upload->id)ですかね

2023-01-11 06:28 UTC, masaton0216 commented on app/Models/Common/Uploads.php
> +    use SoftDeletes;
withTrashed()がマイグレファイルにしかないのは確認済みです。
Laravelの場合、withTrashed()で明示的に抽出指示しないと取得されない認識なんですが、この観点以外で調査観点ありますか？

2023-01-11 06:31 UTC, masaton0216 commented on app/Plugins/Manage/UploadfileManage/UploadfileManage.php
> +        $upload = Uploads::findOrFail($uploads_id);
こんな感じで404返してくれます。Connect-CMSでは記念すべき初利用になります。（OSWS商用ではあります。）
![image](https://user-images.githubusercontent.com/13323806/211734046-81c7f67a-5798-4208-8872-f1a4ad41c392.png)

2023-01-11 06:35 UTC, masaton0216 commented on app/Models/Common/Uploads.php
> +    use SoftDeletes;
Issue元の永原さんの仕様に沿った形で、（私の補足解釈ですが）ファイル系のバックアップ設定をしている運用前提ですが、うっかり削除した場合にデータから復旧作業を追いやすくする為です。

2023-01-11 06:36 UTC, masaton0216 commented on database/migrations/2023_01_11_105812_add_deleted_to_uploads.php
> +{
その指摘内容はむしろ気づいてなかったです。
理由としては牟田さんの指摘への回答にもしましたが、↓になります。
https://github.com/opensource-workshop/connect-cms/pull/1546#discussion_r1066620894

2023-01-11 06:38 UTC, masaton0216 commented on database/migrations/2023_01_11_105812_add_deleted_to_uploads.php
> +            $table->softDeletes();
入らないです。それらのカラムも共通的に追加する設計なんですね。見落としてたので追加します。

2023-01-11 06:39 UTC, masaton0216 commented on resources/views/plugins/manage/uploadfile/index.blade.php
> +
ありがとうございます。取り込みます。

2023-01-11 06:40 UTC, masaton0216 commented on resources/views/plugins/manage/uploadfile/edit.blade.php
> +                        @if ($upload->id)
仰る通り不要なので除去します。

2023-01-11 06:40 UTC, masaton0216 commented on resources/views/plugins/manage/uploadfile/edit.blade.php
> +@if ($upload->id)
仰る通り不要なので除去します。

2023-01-11 06:41 UTC, masaton0216 commented on resources/views/plugins/manage/uploadfile/edit.blade.php
> +                            </a>
ありがとうございます。取り込みます。

2023-01-11 06:43 UTC, gakigaki commented on app/Models/Common/Uploads.php
> +    use SoftDeletes;
<img width="762" alt="image" src="https://user-images.githubusercontent.com/32890286/211736005-d739f94a-cdf6-4e2c-b7cd-8d22f34ae065.png">

こういうクエリビルダが対象になってくるはずで、このSQLは以下です。

> select `databases_input_cols`.*, `databases_columns`.`column_type`, `databases_columns`.`column_name`, `databases_columns`.`classname`, `databases_columns`.`role_display_control_flag`, `databases_columns`.`databases_id`, `databases_columns`.`title_flag`, `databases_columns`.`body_flag`, `uploads`.`client_original_name` from `databases_input_cols` left join `databases_columns` on `databases_columns`.`id` = `databases_input_cols`.`databases_columns_id` left join `uploads` on `uploads`.`id` = `databases_input_cols`.`value` where `databases_inputs_id` = ? order by `databases_inputs_id` asc, `databases_columns_id` asc  

残念ながら、deleted_atを見ていません。

2023-01-11 06:49 UTC, masaton0216 commented on app/Models/Common/Uploads.php
> +    use SoftDeletes;
@gakigaki ありがとうございます。このケースを失念してました。15件程HITしたので確認します。

2023-01-11 07:03 UTC, akagane99 commented on app/Http/Controllers/Core/UploadController.php
> -            return response()->download(storage_path(config('connect.no_image_path')));
・あ、そうでなく、デザイン入れてるサイトで、画像がないとこはno_image表示してとこがあったような？
・そのサイトでno_imageを別のにしてたような。この処理じゃなければ良いのだけれど。

2023-01-11 07:05 UTC, akagane99 commented on app/Plugins/Manage/ManagePluginBase.php
> +    use ConnectCommonTrait;
なるほど。
んじゃUploadfileManage.phpでuse ConnectCommonTrait; に見直しかと。

2023-01-11 07:08 UTC, akagane99 commented on app/Models/Common/Uploads.php
> +    use SoftDeletes;
なるほど。理由理解しました。

そのissueってどれか教えてー。

2023-01-11 07:09 UTC, akagane99 commented on app/Plugins/Manage/UploadfileManage/UploadfileManage.php
> +        $upload = Uploads::findOrFail($uploads_id);
abort(404)と同じか。さんきゅー、問題なしっす

2023-01-11 07:13 UTC, akagane99 commented on app/Models/Common/Uploads.php
> +    use SoftDeletes;
> そのissueってどれか教えてー。

* https://github.com/opensource-workshop/connect-cms-ideas/issues/73#issuecomment-914959407

自己解決。これかな

2023-01-11 07:24 UTC, akagane99 commented on app/Models/Common/Uploads.php
> +    use SoftDeletes;
上記永原さんが目の前にいたので再確認してみた。

> ・ファイルは物理削除
> ・uploadsレコードは論理削除にしたい。（deleted_at を追加）

「うっかり削除は想定してなくて、キャビネットとかフォトアルバムでuploadsレコード消しちゃったら悪影響でるんじゃないか。」

だったようっす。
「今後他も含めて論理削除を検討したいけど、今今は物理削除でええんでない？」

といっとったので、物理削除にしなイカ？
（その方が作業的にも対応少なくなるかとー）

2023-01-11 09:30 UTC, masaton0216 commented on app/Plugins/Manage/ManagePluginBase.php
> +    use ConnectCommonTrait;
元々は個別プラグイン系のコントローラで継承している親クラス（UserPluginBase）で、このConnectCommonTrait使ってまして、管理系のコントローラで継承している親クラス（ManagePluginBase）にも同様に追加した次第です。
ConnectCommonTraitの中身の処理的に、他で共通的に使えそうな内容なので、ManagePluginBaseでもいいかなと考えてますが、どうでしょう？

2023-01-11 09:32 UTC, masaton0216 commented on app/Models/Common/Uploads.php
> +    use SoftDeletes;
確認ありがとうございます。
大元の意向がそのようであれば、論理削除の効用も限定的なので、物理削除に方針変更します。

2023-01-11 09:33 UTC, masaton0216 commented on app/Models/Common/Uploads.php
> +    use SoftDeletes;
物理削除に方針変更したので、本件（上記調査15件の部分）は対応不要になると思います。
諸々、対応したらまた連絡します。

2023-01-12 00:40 UTC, masaton0216 commented on app/Http/Controllers/Core/UploadController.php
> -            return response()->download(storage_path(config('connect.no_image_path')));
社内で確認したところ、このパターン（引数のid = null）の場合だけそのままにしておけば良い、ということだったのでこの部分は元に戻し、以後の部分（3カ所）は404のままにします。

2023-01-12 00:41 UTC, masaton0216 commented on app/Plugins/Manage/ManagePluginBase.php
> +    use ConnectCommonTrait;
社内確認後、何かの折での影響調査のスコープが広がってしまうということから、ミニマムな方（UploadfileManageにuseする）に倒して修正しておきます。

2023-01-12 01:02 UTC, masaton0216 commented
@akagane99 @gakigaki 確認ありがとうございます。諸々、反映済みです。

2023-01-12 01:07 UTC, akagane99 approved these changes
再レビューOK～

2023-01-12 07:42 UTC, gakigaki approved these changes
修正ありがとうございました！

2023-01-13 10:03 UTC, merged