[ログ管理]インストール時に初期値で取得するログの設定を追加しました。
opensource-workshop/connect-cms pull request #2012
Opened 2024-05-14 09:33 UTC by nagasheep

# 概要

インストール時に以下のログは初期値で取得するようにしました。
・ログイン・ログアウト
・メール送信
・パスワード関係
・ユーザ登録

# DB変更の有無

無し

# チェックリスト
- [ ] プルリクエストにわかりやすいタイトルとラベルを付けました。https://github.com/opensource-workshop/connect-cms/wiki/Pull-requests-Rule

2024-05-14 09:44 UTC, akagane99 requested changes
ソース見ました。気になる点が1点ありました。

2024-05-14 09:44 UTC, akagane99 commented on database/seeders/DefaultConfigsTableSeeder.php
> +        if (Configs::where('category', 'app_log')->count() == 0) {
この修正ですと、既存ユーザでapp_log未設定のユーザーにも設定反映され、「勝手に設定された・いやされない」と混乱すると思うのですが意図した動きでしょうか？

2024-05-14 11:02 UTC, nagasheep commented
チェックサンキューです。
指摘は確かに。
明日、修正しますね。

-------------------------------------------------------------
令和6年能登半島地震 子供の学び支援ポータルサイト
https://d-noto.i-school.jp/

つながる未来へ Connect-CMS
https://connect-cms.jp/
-------------------------------------------------------------
株式会社オープンソース・ワークショップ
永原 篤
e-mail ***@***.***
web https://opensource-workshop.jp
電話 03-5534-8088
携帯 090-1699-2746
-------------------------------------------------------------



On Reiwa 6 May 14, Tue at 18:44 Mitsuru Mutaguchi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> ソース見ました。気になる点が1点ありました。
> ------------------------------
>
> In database/seeders/DefaultConfigsTableSeeder.php
> <https://github.com/opensource-workshop/connect-cms/pull/2012#discussion_r1599722250>
> :
>
> > @@ -229,5 +229,31 @@ public function run()
>              ]);
>          }
>
> +        if (Configs::where('category', 'app_log')->count() == 0) {
>
>
> この修正ですと、既存ユーザでapp_log未設定のユーザーにも設定反映され、「勝手に設定された・いやされない」と混乱すると思うのですが意図した動きでしょうか？
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opensource-workshop/connect-cms/pull/2012#pullrequestreview-2054847353>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXP2C4C7PW2FG2KWUNZXETZCHMIPAVCNFSM6AAAAABHVZRZ5KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANJUHA2DOMZVGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-15 03:58 UTC, nagasheep commented
修正してみました。
＆
アップデートもテストして問題なさそうです。

2024-05-16 09:32 UTC, akagane99 commented
修正ありがとうございました。
新規インストールのみ、インストールされるソースコードを確認しました。

確認した流れでマージしちゃいます。

2024-05-16 09:33 UTC, akagane99 approved these changes
レビューOK

2024-05-16 09:33 UTC, merged