[]スライドショー アップロード管理等でファイル削除時、スライドショー管理画面でレコードが表示されなくなるのを修正
opensource-workshop/connect-cms pull request #2018
Opened 2024-05-27 02:25 UTC by masaton0216

# 概要
 - クライアントから問い合わせあり
```
管理画面のアップロードファイルから、スライドショーにアップされた画像を削除すると、スライドショーデータの方にゴミが残ってしまうが、編集画面から当該データを削除できなくなる。
```

# レビュー完了希望日

# 関連Pull requests/Issues

# 参考

# DB変更の有無

有り / 無し

# チェックリスト

- [ ] (DB変更有りの場合) 移行プログラムに影響がない事を確認しました。https://github.com/opensource-workshop/connect-cms/wiki/Pull-requests-check-list---Migration
- [ ] プルリクエストにわかりやすいタイトルとラベルを付けました。https://github.com/opensource-workshop/connect-cms/wiki/Pull-requests-Rule

2024-05-27 03:35 UTC, gakigaki requested changes
no_image画像が出ない件、ご確認お願いします

2024-05-27 03:35 UTC, gakigaki commented on resources/views/plugins/user/slideshows/default/slideshows_edit_row.blade.php
> +                    src="{{ asset("/storage/no_image.png") }}"
パスの指定が間違っていませんか？
私の環境では画像が出てきませんでした。
assetを使うなら以下のファイルでしょうか？
`asset("images/core/no_image/no_image3.png")`

2024-05-27 03:54 UTC, masaton0216 commented on resources/views/plugins/user/slideshows/default/slideshows_edit_row.blade.php
> +                    src="{{ asset("/storage/no_image.png") }}"
@gakigaki 
自分のローカル `php artisan storage:link` してたから参照出来てただけでご指摘通り、パス指定が誤っておりました。
修正済みです。ご確認ください。

2024-05-27 08:55 UTC, gakigaki approved these changes
修正ありがとうございます。
私はOKです！

2024-05-28 01:07 UTC, osws-makino commented
確認しました。ありがとうございます！

2024-05-28 01:15 UTC, merged