キャビネットプラグインの機能追加
opensource-workshop/connect-cms pull request #910
Opened 2021-06-18 11:35 UTC by gakigaki

## 概要
キャビネット機能の要望があり、機能追加しました。
NetCommonsにもあった機能になります。

## 関連Pull requests/Issues
https://github.com/opensource-workshop/connect-cms-ideas/issues/47

## 参考

## DB変更の有無
あり

有り / 無し

## チェックリスト

- [ ] PHP_CodeSnifferを実行して、本PR内に指摘が存在しないことを確認しました。https://github.com/opensource-workshop/connect-cms/wiki/PHP_CodeSniffer

- [ ] オンラインマニュアルの更新 https://connect-cms.jp/manual

2021-06-22 07:17 UTC, akagane99 requested changes
レビューしました。

2021-06-22 07:17 UTC, akagane99 commented on resources/views/plugins/user/cabinets/default/bucket.blade.php
> +            <label class="{{$frame->getSettingLabelClass()}}" for="upload-max-size">ファイル最大サイズ</label>
upload_max_size はどっかで ini_set()しない？

参考記事
https://qiita.com/nagahama/items/7ab9dab0085faa480315

2021-06-22 07:25 UTC, akagane99 commented on resources/views/plugins/user/cabinets/default/bucket.blade.php
> +            <label class="{{$frame->getSettingLabelClass()}}" for="upload-max-size">ファイル最大サイズ</label>
NC2は、１ファイルの最大サイズなのか。勘違いしてた。
![image](https://user-images.githubusercontent.com/2756509/122881738-7061ee80-d376-11eb-8934-b641dc6320ea.png)

2021-06-22 07:30 UTC, akagane99 commented on resources/views/plugins/user/cabinets/default/index.blade.php
> +            </div>
これ入れて欲しいな。
https://github.com/opensource-workshop/connect-cms/issues/283

2021-06-22 08:07 UTC, gakigaki commented on database/migrations/2021_06_01_144324_create_cabinet_frames.php
> +        Schema::create('cabinet_frames', function (Blueprint $table) {
消し忘れです。消します。

2021-06-22 08:24 UTC, gakigaki commented on database/migrations/2021_06_01_151825_create_cabinets.php
> +            $table->integer('approval_flag')->default(0)->comment('承認フラグ');
今後用ですね。
この前、画面を見ていただいたときに挙がった件です。

2021-06-22 08:37 UTC, gakigaki commented on app/Plugins/User/Cabinets/CabinetsPlugin.php
> +        $this->makeZip($save_path, $request);
今のところ消すタイミングはないです。
どこかいいタイミングありますかね？
ダウンロード処理走るときに古いtmpのzipがあったら消すとかはどうですか？

2021-06-22 08:42 UTC, akagane99 commented on app/Plugins/User/Cabinets/CabinetsPlugin.php
> +        $this->makeZip($save_path, $request);
そうだよねぇ。

> ダウンロード処理走るときに古いtmpのzipがあったら消すとかはどうですか？

多分ダウンロードと、別の人がzipダウンロードが被るとバグるような気がするっす。

よし、今はそのままでOKです。
今後Connect-CMS全体で、ごみファイル削除（ファイルクリーンアップ）機能作った時に、消す感じかなぁと。

2021-06-22 08:44 UTC, gakigaki commented on app/Plugins/User/Cabinets/CabinetsPlugin.php
> +        $this->makeZip($save_path, $request);
たとえばファイルの更新日時見て、○日前なら削除とかどうですか？
https://baccholog.com/archives/949

2021-06-22 08:46 UTC, akagane99 commented on app/Plugins/User/Cabinets/CabinetsPlugin.php
> +        $this->makeZip($save_path, $request);
お、１日？たっちゃえば消しちゃって問題なさそうね。

2021-06-22 08:52 UTC, gakigaki commented on app/Plugins/User/Cabinets/CabinetsPlugin.php
> +        $this->makeZip($save_path, $request);
1日でいいと思います。
では更新日時が一日以前だったら消す処理入れておきます！

2021-06-22 09:03 UTC, akagane99 commented on app/Plugins/User/Cabinets/CabinetsPlugin.php
> +        $this->makeZip($save_path, $request);
こんなのもあるみたい。

https://qiita.com/a_yasui/items/0a9c8b7456188e566303
```php
        // deleteFileAfterSend( true ) とすることでファイルをダウンロードしたと同時に削除をする
        return \Response::download($tmp_file, 'hoge-' . date('Ymd') . '.csv')
            ->deleteFileAfterSend( true );
```

2021-06-23 09:13 UTC, gakigaki commented on database/migrations/2021_06_01_144324_create_cabinet_frames.php
> +        Schema::create('cabinet_frames', function (Blueprint $table) {
上に記載した通り、
create_cabinet_framesは削除します。

2021-06-23 09:29 UTC, gakigaki commented on app/Plugins/User/Cabinets/CabinetsPlugin.php
> +        $this->makeZip($save_path, $request);
対応案のご提示ありがとうございます。
symfonyにあるdeleteFileAfterSend()を利用して、送信後削除するようにします。
https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php

2021-06-23 09:39 UTC, gakigaki commented on resources/views/plugins/user/cabinets/default/bucket.blade.php
> +            <label class="{{$frame->getSettingLabelClass()}}" for="upload-max-size">ファイル最大サイズ</label>
@akagane99
リンク先を確認しました。
post_max_size、upload_max_filesizeはini_set()で変更できないようです。

2021-06-23 09:50 UTC, gakigaki commented on resources/views/plugins/user/cabinets/default/index.blade.php
> +            </div>
@akagane99 
フレームの設定画面と、ファイルアップロードする2か所にコメント入れてみました。
いかがでしょうか？
![image](https://user-images.githubusercontent.com/32890286/123075852-8beef700-d453-11eb-9f49-fcd7d3b51c6d.png)
![image](https://user-images.githubusercontent.com/32890286/123076088-c3f63a00-d453-11eb-833c-bf4f600f08bd.png)

2021-06-23 10:06 UTC, akagane99 commented on resources/views/plugins/user/cabinets/default/bucket.blade.php
> +            <label class="{{$frame->getSettingLabelClass()}}" for="upload-max-size">ファイル最大サイズ</label>
あら？
モードが `PHP_INI_ALL` なら変更できるみたいだけど、違ってたって事かな？

2021-06-23 10:06 UTC, akagane99 commented on resources/views/plugins/user/cabinets/default/index.blade.php
> +            </div>
ばっちりです。

2021-06-23 10:35 UTC, gakigaki commented on resources/views/plugins/user/cabinets/default/index.blade.php
> +            </div>
上の画像はini_get('upload_max_filesize')を出力するようにして、
下の画像は上で選んだ値を出すようのします。

2021-06-23 10:39 UTC, gakigaki commented
ご指摘内容の修正が完了しました。
ご確認お願いします。

2021-06-23 12:21 UTC, akagane99 commented on resources/views/plugins/user/cabinets/default/bucket.blade.php
> +            <label class="{{$frame->getSettingLabelClass()}}" for="upload-max-size">ファイル最大サイズ</label>
牟田口勘違いでした。
セットできない。

2021-06-23 12:25 UTC, akagane99 commented
確認しました。

2021-06-23 12:26 UTC, merged

2021-06-23 12:30 UTC, akagane99 commented
オンラインマニュアル、公開しました。
https://connect-cms.jp/manual/user/cabinet